# Lista 3
Arthur Pontes de Miranda Ramos Soares

In [2]:
import numpy as np
import cv2 as cv
import matplotlib.pyplot as plt

## Funções Auxiliares

In [3]:
def show_images(*images: np.ndarray, titles: list[str] | None = None, columns: int = 2, scale: int = 5) -> None:
    num_images = len(images)
    
    if titles is None:
        titles = [f'Image {i+1}' for i in range(num_images)]
    
    rows = (num_images + columns - 1) // columns 

    fig, axes = plt.subplots(rows, columns, figsize=(scale * columns, scale * rows))
    axes = np.array(axes).reshape(rows, columns)

    for ax, img, title in zip(axes.flat, images, titles):
        ax.imshow(img)
        ax.set_title(title)

    for i in range(num_images, rows * columns):
        fig.delaxes(axes.flat[i])

    plt.tight_layout()

def show_image(image: np.ndarray, title: str = None, dpi: int = 100) -> None:
    height, width, _ = image.shape
    
    figsize = (width / dpi, height / dpi)
    
    plt.figure(figsize=figsize, dpi=dpi)
    plt.imshow(image, cmap='gray' if len(image.shape) == 2 else None)
    plt.title(title if title else "")

    plt.tight_layout()

## Questão 1

In [5]:
N_MATCHES = 14
def match_sift(filename1: str, filename2: str):
    img1 = cv.imread(filename1, cv.IMREAD_GRAYSCALE)
    img2 = cv.imread(filename2, cv.IMREAD_GRAYSCALE)

    sift = cv.SIFT_create()
    kp1, des1 = sift.detectAndCompute(img1, None)
    kp2, des2 = sift.detectAndCompute(img2, None)

    bf = cv.BFMatcher(cv.NORM_L2, crossCheck=True)

    matches = bf.match(des1, des2)
    matches = sorted(matches, key = lambda x:x.distance)
    
    return kp1, kp2, matches

filenames = [('praia-1', 'praia-2')]
for filename1, filename2 in filenames:
    kp1, kp2, matches = match_sift(f'./assets/{filename1}.jpg', f'./assets/{filename2}.jpg')

    src = np.float32([kp1[m.queryIdx].pt for m in matches[:4]]).reshape(-1, 2)
    dst = np.float32([kp2[m.trainIdx].pt for m in matches[:4]]).reshape(-1, 2)

    transform_mat = cv.getPerspectiveTransform(src, dst)
 
    print(transform_mat)

[[ 1.41794916e+00 -1.05458776e+00  6.22317371e+02]
 [ 4.03613720e-01  1.93580647e-01  1.36616745e+02]
 [ 8.15723400e-04 -1.27284317e-03  1.00000000e+00]]
